registerDQ10Craft({
  id: "sewing",
  label: "裁縫",
  modeLabel: "Sewing Settings",
  recipeLabel: "装備名",
  itemNameLabel: "マス名",
  resourceLabel: "集中力",
  stateLabel: "ぬいパワー",
  defaultRecipeName: "裁縫メモ",
  defaultFocus: 145,
  focus: createDQ10FocusConfig({
    defaultFocus: 145,
    defaultLevel: 80,
    defaultToolId: "sewing-needle",
    defaultStars: 3,
    toolTypes: [{ id: "sewing-needle", label: "さいほう針" }],
  }),
  layout: {
    label: "布配置",
    columns: 3,
    rows: 3,
    fixed: false,
  },
  heatStates: DQ10SewingDamage.powerStates,
  techniques: [
    { id: "sew", name: "ぬう", focusCost: 5, damageModel: "sewing-power", actionId: "sew", multiplier: 1, criticalMultiplier: 2, criticalWeight: 1 },
    { id: "half", name: "半かげんぬい", focusCost: 6, damageModel: "sewing-power", actionId: "half", multiplier: 0.5, criticalMultiplier: 2, criticalWeight: 0.8 },
    { id: "double", name: "2倍ぬい", focusCost: 8, damageModel: "sewing-power", actionId: "double", multiplier: 2, criticalMultiplier: 2, criticalWeight: 0.9 },
    { id: "triple", name: "3倍ぬい", focusCost: 12, damageModel: "sewing-power", actionId: "triple", multiplier: 3, criticalMultiplier: 2, criticalWeight: 0.85 },
    { id: "aim", name: "ねらいぬい", focusCost: 16, damageModel: "sewing-power", actionId: "sew", multiplier: 1, criticalMultiplier: 2, criticalWeight: 1.8 },
    { id: "loosen", name: "ほぐしぬい", focusCost: 8, damageModel: "sewing-power", actionId: "loosen", multiplier: -1, criticalMultiplier: 1, criticalWeight: 0.6 },
    { id: "wind-center", name: "巻きこみ中心", focusCost: 10, damageModel: "sewing-power", actionId: "wind_center", multiplier: 1.5, criticalMultiplier: 2, criticalWeight: 0.8 },
    { id: "wind-around", name: "巻きこみ周り", focusCost: 10, damageModel: "sewing-power", actionId: "wind_around", multiplier: 0.75, criticalMultiplier: 2, criticalWeight: 0.8 },
  ],
  items: [
    { id: "part-1", name: "左上", gridCell: { row: 1, column: 1 }, current: 0, successMin: 70, successMax: 85 },
    { id: "part-2", name: "中央上", gridCell: { row: 1, column: 2 }, current: 0, successMin: 70, successMax: 85 },
    { id: "part-3", name: "右上", gridCell: { row: 1, column: 3 }, current: 0, successMin: 70, successMax: 85 },
    { id: "part-4", name: "左下", gridCell: { row: 3, column: 1 }, current: 0, successMin: 70, successMax: 85 },
    { id: "part-5", name: "中央下", gridCell: { row: 3, column: 2 }, current: 0, successMin: 70, successMax: 85 },
    { id: "part-6", name: "右下", gridCell: { row: 3, column: 3 }, current: 0, successMin: 70, successMax: 85 },
  ],
});
