registerDQ10Craft({
  id: "weapon-smithing",
  label: "武器鍛冶",
  modeLabel: "Weapon Smithing Settings",
  recipeLabel: "装備名",
  itemSectionTitle: "鍛冶マス入力",
  itemNameLabel: "マス名",
  addItemLabel: "マスを追加",
  resourceLabel: "集中力",
  turnLabel: "残り手数",
  stateLabel: "温度",
  defaultRecipeName: "武器メモ",
  defaultFocus: 140,
  focus: createDQ10FocusConfig({
    defaultFocus: 140,
    defaultLevel: 80,
    defaultToolId: "smithing-hammer",
    defaultStars: 3,
    toolTypes: [{ id: "smithing-hammer", label: "鍛冶ハンマー" }],
  }),
  defaultTurns: 10,
  layout: {
    label: "鍛冶配置",
    columns: 2,
    rows: 4,
    fixed: false,
  },
  heatStates: DQ10SmithingDamage.heatStates,
  techniques: [
    { id: "hit", name: "たたく", focusCost: 5, damageModel: "smithing-temperature", powerId: "normal", multiplier: 1, criticalMultiplier: 2, criticalWeight: 1 },
    { id: "double", name: "2倍打ち", focusCost: 8, damageModel: "smithing-temperature", powerId: "power_2_0", multiplier: 2, criticalMultiplier: 2, criticalWeight: 0.9 },
    { id: "half", name: "半減打ち", focusCost: 6, damageModel: "smithing-temperature", powerId: "power_0_5", multiplier: 0.5, criticalMultiplier: 2, criticalWeight: 0.8 },
    { id: "aim", name: "ねらい打ち", focusCost: 16, damageModel: "smithing-temperature", powerId: "normal", multiplier: 1, criticalMultiplier: 2, criticalWeight: 1.8 },
  ],
  items: [
    { id: "part-1", name: "上段", gridCell: { row: 1, column: 1 }, current: 0, successMin: 80, successMax: 95 },
    { id: "part-2", name: "中段", gridCell: { row: 2, column: 1 }, current: 0, successMin: 80, successMax: 95 },
    { id: "part-3", name: "下段", gridCell: { row: 3, column: 1 }, current: 0, successMin: 80, successMax: 95 },
  ],
});
