registerDQ10Craft({
  id: "cooking",
  label: "調理職人",
  modeLabel: "Cooking Craft MVP",
  recipeLabel: "料理名",
  itemSectionTitle: "調理状態入力",
  itemNameLabel: "具材名",
  itemOptionLabel: "場所",
  addItemLabel: "具材を追加",
  resourceLabel: "集中力",
  turnLabel: "残りターン",
  stateLabel: "火力状態",
  defaultRecipeName: "料理メモ",
  defaultFocus: 120,
  focus: createDQ10FocusConfig({
    defaultFocus: 120,
    defaultLevel: 80,
    defaultToolId: "frying-pan",
    defaultStars: 3,
    toolTypes: [{ id: "frying-pan", label: "フライパン" }],
  }),
  defaultTurns: 8,
  defaultRecipeTrait: "none",
  recipeTraits: [
    { id: "none", label: "なし" },
    { id: "glow", label: "光" },
    { id: "glow-return", label: "光・戻り" },
  ],
  layout: {
    label: "フライパン配置",
    columns: 3,
    rows: 3,
    fixed: true,
  },
  itemOptions: DQ10CookingDamage.positions,
  techniquePreviewOptionId: "center",
  heatStates: DQ10CookingDamage.heatStates,
  techniques: [
    {
      id: "basic",
      name: "このまま焼く",
      focusCost: DQ10CookingDamage.actions.basic.focusCost,
      damageModel: "cooking-fixed",
      actionId: "basic",
      conditionId: DQ10CookingDamage.actions.basic.conditionId,
      multiplier: DQ10CookingDamage.actions.basic.multiplier,
      criticalMultiplier: DQ10CookingDamage.actions.basic.criticalMultiplier,
      criticalWeight: 1,
    },
    {
      id: "weak",
      name: "弱火焼き",
      focusCost: DQ10CookingDamage.actions.weak.focusCost,
      damageModel: "cooking-fixed",
      actionId: "weak",
      conditionId: DQ10CookingDamage.actions.weak.conditionId,
      multiplier: DQ10CookingDamage.actions.weak.multiplier,
      criticalMultiplier: DQ10CookingDamage.actions.weak.criticalMultiplier,
      criticalWeight: 0.8,
    },
    {
      id: "strong",
      name: "強火焼き",
      focusCost: DQ10CookingDamage.actions.strong.focusCost,
      damageModel: "cooking-fixed",
      actionId: "strong",
      conditionId: DQ10CookingDamage.actions.strong.conditionId,
      multiplier: DQ10CookingDamage.actions.strong.multiplier,
      criticalMultiplier: DQ10CookingDamage.actions.strong.criticalMultiplier,
      criticalWeight: 0.9,
    },
    {
      id: "aim",
      name: "ねらい焼き",
      focusCost: DQ10CookingDamage.actions.aim.focusCost,
      damageModel: "cooking-fixed",
      actionId: "aim",
      conditionId: DQ10CookingDamage.actions.aim.conditionId,
      multiplier: DQ10CookingDamage.actions.aim.multiplier,
      criticalMultiplier: DQ10CookingDamage.actions.aim.criticalMultiplier,
      criticalWeight: 1.8,
    },
  ],
  items: [
    { id: "slot-1", name: "左上", optionId: "corner", gridCell: { row: 1, column: 1 }, current: 0, successMin: 60, successMax: 75 },
    { id: "slot-2", name: "上", optionId: "cross", gridCell: { row: 1, column: 2 }, current: 0, successMin: 60, successMax: 75 },
    { id: "slot-3", name: "右上", optionId: "corner", gridCell: { row: 1, column: 3 }, current: 0, successMin: 60, successMax: 75 },
    { id: "slot-4", name: "左", optionId: "cross", gridCell: { row: 2, column: 1 }, current: 0, successMin: 60, successMax: 75 },
    { id: "slot-5", name: "中央", optionId: "center", gridCell: { row: 2, column: 2 }, current: 0, successMin: 60, successMax: 75 },
    { id: "slot-6", name: "右", optionId: "cross", gridCell: { row: 2, column: 3 }, current: 0, successMin: 60, successMax: 75 },
    { id: "slot-7", name: "左下", optionId: "corner", gridCell: { row: 3, column: 1 }, current: 0, successMin: 60, successMax: 75 },
    { id: "slot-8", name: "下", optionId: "cross", gridCell: { row: 3, column: 2 }, current: 0, successMin: 60, successMax: 75 },
    { id: "slot-9", name: "右下", optionId: "corner", gridCell: { row: 3, column: 3 }, current: 0, successMin: 60, successMax: 75 },
  ],
});
