registerDQ10Craft({
  id: "cooking",
  label: "調理職人",
  modeLabel: "Cooking Craft MVP",
  recipeLabel: "料理名",
  itemNameLabel: "具材名",
  allowCustomRecipes: false,
  resourceLabel: "集中力",
  stateLabel: "火力状態",
  defaultRecipeName: "料理メモ",
  targetMode: "random-in-range",
  focusNote: "Lv76-80はLv75以降を各レベル+2として置いた暫定値です。",
  defaultTraitId: "light",
  traits: [
    {
      id: "light",
      label: "光",
      description: "4ターンごとに、食材が置いてあるランダムな1マスが光ります。",
    },
    {
      id: "light-return",
      label: "光・戻り",
      description: "4ターンごとに上下左右が光ります。次の4ターン後には四隅が戻り、以後交互に訪れます。",
    },
    {
      id: "recovery",
      label: "回復",
      description: "4ターンごとに、基準値外の食材が回復します。",
    },
  ],
  defaultFocus: 247,
  focus: createDQ10FocusConfig({
    defaultFocus: 247,
    defaultLevel: 80,
    defaultToolId: "miracle-frying-pan",
    defaultStars: 3,
    levels: getDQ10FocusLevels("cooking"),
    toolTypes: getDQ10FocusToolTypes("fryingPan"),
  }),
  defaultTurns: 8,
  layout: {
    label: "フライパン配置",
    columns: 3,
    rows: 3,
    fixed: true,
  },
  itemOptions: DQ10CookingDamage.positions,
  techniquePreviewOptionId: "center",
  heatStates: DQ10CookingDamage.heatStates,
  techniques: [
    {
      id: "current-heat",
      name: "現在火力",
      focusCost: 0,
      damageModel: "cooking-fixed",
      actionId: "current-heat",
      conditionId: null,
      criticalMultiplier: 2,
      criticalWeight: 1,
      showInTechniqueEditor: false,
      recommendable: false,
    },
    {
      id: "miracle-grill",
      name: "ミラクルグリル",
      focusCost: 0,
      normalMin: 0,
      normalMax: 0,
      criticalMin: 0,
      criticalMax: 0,
      criticalWeight: 2,
      specialAction: "miracle-grill",
      includeInAnalysis: false,
    },
    {
      id: "half-seal",
      name: "半熟封じ",
      focusCost: 0,
      damageModel: "cooking-effect",
      effectType: "ingredient-block",
      effectId: "half-seal",
      effectSummary: "ダメージ半減",
      effectDurationLabel: "4ターン",
      includeInAnalysis: false,
      recommendable: false,
    },
    {
      id: "full-seal",
      name: "完熟封じ",
      focusCost: 0,
      damageModel: "cooking-effect",
      effectType: "ingredient-block",
      effectId: "full-seal",
      effectSummary: "ダメージ・回復無効",
      effectDurationLabel: "4ターン",
      includeInAnalysis: false,
      recommendable: false,
    },
    {
      id: "heat-return",
      name: "焼き戻し",
      focusCost: 0,
      damageModel: "cooking-effect",
      effectType: "cell-return",
      effectId: "heat-return",
      effectSummary: "焼かずに回復",
      effectDurationLabel: "4ターン",
      includeInAnalysis: false,
      recommendable: false,
    },
  ],
  items: [
    { id: "slot-1", name: "左上", optionId: "corner", gridCell: { row: 1, column: 1 }, current: 0, successMin: 60, successMax: 75 },
    { id: "slot-2", name: "上", optionId: "cross", gridCell: { row: 1, column: 2 }, current: 0, successMin: 60, successMax: 75 },
    { id: "slot-3", name: "右上", optionId: "corner", gridCell: { row: 1, column: 3 }, current: 0, successMin: 60, successMax: 75 },
    { id: "slot-4", name: "左", optionId: "cross", gridCell: { row: 2, column: 1 }, current: 0, successMin: 60, successMax: 75 },
    { id: "slot-5", name: "中央", optionId: "center", gridCell: { row: 2, column: 2 }, current: 0, successMin: 60, successMax: 75 },
    { id: "slot-6", name: "右", optionId: "cross", gridCell: { row: 2, column: 3 }, current: 0, successMin: 60, successMax: 75 },
    { id: "slot-7", name: "左下", optionId: "corner", gridCell: { row: 3, column: 1 }, current: 0, successMin: 60, successMax: 75 },
    { id: "slot-8", name: "下", optionId: "cross", gridCell: { row: 3, column: 2 }, current: 0, successMin: 60, successMax: 75 },
    { id: "slot-9", name: "右下", optionId: "corner", gridCell: { row: 3, column: 3 }, current: 0, successMin: 60, successMax: 75 },
  ],
});
