registerDQ10Craft({
  id: "pot-alchemy",
  label: "ツボ錬金",
  modeLabel: "Pot Alchemy Settings",
  recipeLabel: "錬金名",
  itemSectionTitle: "錬金スロット入力",
  itemNameLabel: "スロット名",
  addItemLabel: "スロットを追加",
  resourceLabel: "集中力",
  turnLabel: "残り手数",
  stateLabel: "状態",
  defaultRecipeName: "ツボ錬金メモ",
  defaultFocus: 100,
  focus: createDQ10FocusConfig({
    defaultFocus: 100,
    defaultLevel: 80,
    defaultToolId: "alchemy-pot",
    defaultStars: 3,
    toolTypes: [{ id: "alchemy-pot", label: "錬金ツボ" }],
  }),
  defaultTurns: 6,
  heatStates: [
    { id: "normal", label: "通常" },
    { id: "risk-up", label: "リスク上昇" },
    { id: "chance", label: "チャンス" },
    { id: "special", label: "特殊効果中" },
  ],
  techniques: [
    { id: "basic", name: "通常錬金", focusCost: 0, normalMin: 10, normalMax: 16, criticalMin: 20, criticalMax: 32, criticalWeight: 1 },
    { id: "safe", name: "安全寄せ", focusCost: 8, normalMin: 6, normalMax: 10, criticalMin: 12, criticalMax: 20, criticalWeight: 0.9 },
    { id: "power", name: "強めに回す", focusCost: 12, normalMin: 18, normalMax: 28, criticalMin: 36, criticalMax: 56, criticalWeight: 0.85 },
    { id: "aim", name: "大成功狙い", focusCost: 18, normalMin: 10, normalMax: 16, criticalMin: 20, criticalMax: 32, criticalWeight: 1.7 },
  ],
  items: [
    { id: "slot-1", name: "効果 1", current: 0, successMin: 55, successMax: 75 },
    { id: "slot-2", name: "効果 2", current: 0, successMin: 55, successMax: 75 },
    { id: "slot-3", name: "効果 3", current: 0, successMin: 55, successMax: 75 },
  ],
});
