registerDQ10Craft({
  id: "armor-smithing",
  label: "防具鍛冶",
  modeLabel: "Armor Smithing Settings",
  recipeLabel: "装備名",
  itemSectionTitle: "鍛冶マス入力",
  itemNameLabel: "マス名",
  addItemLabel: "マスを追加",
  resourceLabel: "集中力",
  stateLabel: "温度",
  defaultRecipeName: "防具メモ",
  targetMode: "random-in-range",
  focusNote: "Lv76-80はLv75以降を各レベル+2として置いた暫定値です。",
  defaultFocus: 247,
  focus: createDQ10FocusConfig({
    defaultFocus: 247,
    defaultLevel: 80,
    defaultToolId: "miracle-smithing-hammer",
    defaultStars: 3,
    levels: getDQ10FocusLevels("smithing"),
    toolTypes: getDQ10FocusToolTypes("smithingHammer"),
  }),
  layout: {
    label: "鍛冶配置",
    columns: 2,
    rows: 4,
    fixed: false,
  },
  heatStates: DQ10SmithingDamage.heatStates,
  techniques: [
    { id: "hit", name: "たたく", focusCost: 5, damageModel: "smithing-temperature", powerId: "normal", multiplier: 1, criticalMultiplier: 2, criticalWeight: 1 },
    { id: "top-bottom", name: "上下打ち", focusCost: 8, damageModel: "smithing-temperature", powerId: "power_1_2", multiplier: 1.2, criticalMultiplier: 2, criticalWeight: 0.95 },
    { id: "quad", name: "4連打ち", focusCost: 12, damageModel: "smithing-temperature", powerId: "power_1_2", multiplier: 1.2, criticalMultiplier: 2, criticalWeight: 0.9 },
    { id: "aim", name: "ねらい打ち", focusCost: 16, damageModel: "smithing-temperature", powerId: "normal", multiplier: 1, criticalMultiplier: 2, criticalWeight: 1.8 },
  ],
  items: [
    { id: "part-1", name: "左上", gridCell: { row: 1, column: 1 }, current: 0, successMin: 80, successMax: 95 },
    { id: "part-2", name: "右上", gridCell: { row: 1, column: 2 }, current: 0, successMin: 80, successMax: 95 },
    { id: "part-3", name: "左下", gridCell: { row: 2, column: 1 }, current: 0, successMin: 80, successMax: 95 },
    { id: "part-4", name: "右下", gridCell: { row: 2, column: 2 }, current: 0, successMin: 80, successMax: 95 },
  ],
});
